### ISSUE TITLE
Monterey patch

### ISSUE THREAD

**Issue by davidAlaBer** [Lorys89/DELL_OPTIPLEX_9020_USFF#1]
**wifi/bt patch.** Any suggestion regarding this for a Monterey update?
https://dortania.github.io/OpenCore-Legacy-Patcher/MONTEREY-DROP.html#wireless-support-dropped

**Comment by Lorys89** [comment]
I already have monterey beta 5 on this PC, soon I update the efi.

**Comment by davidAlaBer** [comment]
Thanks for replying soon.

**Comment by davidAlaBer** [comment]
Please can you update the efi for Monterey?
