### ISSUE TITLE
Monterey Update

### ISSUE THREAD

**Issue by davidAlaBer** [Lorys89/DELL_OPTIPLEX_9020_USFF#2]
Hello!
System Update invites to me to update to Monterey. Is it safe or do I need to update EFI or Opencore version?

**Comment by Lorys89** [comment]
change smbios, use imac 16.x or 17.x

**Comment by Lorys89** [comment]
> I updated oc and os version but I can't make Bt works. Firmware is not loaded. Did you fix this issue?

https://github.com/Lorys89/DELL_OPTIPLEX_9020_USFF/releases/download/0.7.5/EFI.zip

**Comment by davidAlaBer** [comment]
I will try it soon.

**Comment by davidAlaBer** [comment]
It worked very well no issues at the moment. Thanks
